### ISSUE TITLE
I am getting this error when i am executing the code

### ISSUE THREAD

**Issue by ghost** [ahmedgulabkhan/GroupChatApp#10]

**Comment by Shinji7700** [comment]
E/flutter (22983): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (22983): #0      List.[] (dart:core-patch/growable_array.dart:146:60)
E/flutter (22983): #1      DatabaseService.getUserData (package:flutter_app/services/database_service.dart:98:29)
E/flutter (22983): <asynchronous suspension>
E/flutter (22983): #2      _SignInPageState._onSignIn.<anonymous closure> (package:flutter_app/pages/SignIn.dart:39:68)
E/flutter (22983): #3      _SignInPageState._onSignIn.<anonymous closure> (package:flutter_app/pages/SignIn.dart:37:68)
E/flutter (22983): #4      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (22983): #5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (22983): #6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (22983): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (22983): #8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (22983): #9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (22983): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (22983): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (22983): #12     AuthService.signInwithEmailAndPassword (package:flutter_app/services/auth_service.dart)
E/flutter (22983): #13     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (22983): #14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (22983): #15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (22983): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (22983): #17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (22983): #18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (22983): #19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (22983): #20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (22983): #21     FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart)
E/flutter (22983): #22     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (22983): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (22983): #24     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (22983): #25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (22983): #26     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (22983): #27     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (22983): #28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (22983): #29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (22983): #30     MethodChannelFirebaseAuth.signInWithCredential (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart)
E/flutter (22983): #31     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (22983): #32     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (22983): #33     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (22983): #34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (22983): #35     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (22983): #36     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (22983): #37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (22983): #38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (22983): #39     MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (22983): #40     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (22983): #41     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (22983): #42     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (22983): #43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (22983): #44     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (22983): #45     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (22983): #46     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (22983): #47     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (22983): #48     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (22983): #49     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (22983): #50     _CustomZone.runUnary (dart:async/zone.dart:1085:19)

**Comment by Shinji7700** [comment]
How to clear this help me
